dry-random:
  mode: dry
  input_mint: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
  output_mint: So11111111111111111111111111111111111111112
  provider: AsyncJupiterProvider
  strategy:
    name: RandomStrategy
    params:
      buy_chance: '40'
      sell_chance: '20'
  notifier: NullNotificationService

run-composer-wma:
  mode: real
  keypair: ${WALLET_PRIVATE_KEY}
  input_mint: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
  output_mint: So11111111111111111111111111111111111111112
  provider: AsyncJupiterProvider
  strategy:
    name: StrategyComposer
    params:
      buy_mode: all
      sell_mode: any
      buy_strategies:
        - name: WeightedMovingAverageStrategy
          params:
            short_window: 15
            long_window: 100
            buy_when_short_below: true
            period: 15
            shift_past: 0
      sell_strategies:
        - name: TargetPercentStrategy
          params:
            target_percent: '6.01'
            balance_percent: '0.80'
  notifier: NullNotificationService
